// Code generated by MockGen. DO NOT EDIT.
// Source: backend/repositories/UserRepository.go
//
// Generated by this command:
//
//	mockgen -source=backend/services/UserService.go -source=backend/repositories/UserRepository.go -destination=mocks/LoginMock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
