// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/UserRepository.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/UserService.go -source=internal/repositories/UserRepository.go -destination=mocks/LoginMock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
